### ISSUE TITLE
Build failure with 6.1.5

### ISSUE THREAD

**Issue by EmergReanimator** [ivanovborislav/rtl8812au#2]
Thank you for your great job so far!

Recently I have faced the number compilation issues with 6.1.5 kernel.

Do you see any chance to fix them soon?
[build_failure.txt](https://github.com/ivanovborislav/rtl8812au/files/10460546/build_failure.txt)

**Comment by ivanovborislav** [comment]
Hi!
Patch driver and recompile again please.
```
cd rtl8812au
wget https://raw.githubusercontent.com/ivanovborislav/document/main/patch/rtl8812au_v5.13.6_k-6.1-rc5.patch
patch -p1 < rtl8812au_v5.13.6_k-6.1-rc5.patch
```
I will add support soon.

**Comment by ivanovborislav** [comment]
Hello again!

Now is added kernel 6.2 support (successful compiled on kernel 6.1-rc5, 6.1.5 and 6.2-rc3). NO patch required!

**Comment by EmergReanimator** [comment]
@ivanovborislav  Absolutely marvelous!
Works like a charm! I wish the other things in the world got fixed so quickly.

```
Testing download speed................................................................................
Download: 130.52 Mbit/s
Testing upload speed......................................................................................................
Upload: 45.12 Mbit/s
```

**Comment by ivanovborislav** [comment]
I am happy to help!

**Comment by compicat** [comment]
> I am happy to help!

Thanks for great work. Can you make it compatible with 6.3 kernel (now it is in rc2)?

**Comment by ivanovborislav** [comment]
Hi!
Patch driver and recompile again.
```
cd rtl8812au
wget https://raw.githubusercontent.com/ivanovborislav/document/main/patch/rtl8812au_v5.13.6_k-v6.3-rc2.patch
patch -p1 < rtl8812au_v5.13.6_k-v6.3-rc2.patch
```
I didn't have time to test it, I just compiled successfully the driver.

**Comment by compicat** [comment]
> Hi! Patch driver and recompile again.
> 
> ```
> cd rtl8812au
> wget https://raw.githubusercontent.com/ivanovborislav/document/main/patch/rtl8812au_v5.13.6_k-v6.3-rc2.patch
> patch -p1 < rtl8812au_v5.13.6_k-v6.3-rc2.patch
> ```
> 
> I didn't have time to test it, I just compiled successfully the driver.

Thank you so much for fastest action! Gonna try and report

**Comment by compicat** [comment]
@ivanovborislav Thank you! I ve tested with my custom kernel and linux-mainline. It is working flawless with your patch

**Comment by ivanovborislav** [comment]
You're welcome!

**Comment by compicat** [comment]
Hello @ivanovborislav,

Hope you are well. Can you make a patch for 6.4 rc1 too when you have time?

Thanks in advance.

**Comment by compicat** [comment]
I am sorry, it compiled 6.4 without problem with last 6.3 patch. Thanks again.

**Comment by ivanovborislav** [comment]
OK.

**Comment by compicat** [comment]
Hi, hope you are well. It has started not to work with 6.4.6 and linux 6.5 rc2. Thanks in advance.
